-- Matches display architecture support.
-- Run this once before deploying the app code that reads competitions.display_type.

alter table public.competitions
  add column if not exists display_type text not null default 'LEAGUE';

alter table public.competitions
  drop constraint if exists competitions_display_type_check;

alter table public.competitions
  add constraint competitions_display_type_check
  check (display_type in ('LEAGUE', 'LEAGUE_KNOCKOUT', 'GROUPS_KNOCKOUT'));

update public.competitions
set display_type = case
  when lower(type) = 'league' then 'LEAGUE'
  when lower(type) = 'cup' then 'GROUPS_KNOCKOUT'
  else display_type
end;

create table if not exists public.competition_group_standings (
  id bigint generated by default as identity primary key,
  competition_id int not null references public.competitions(id) on delete cascade,
  season_id int,
  "group" text not null,
  position int not null,
  team_id int not null references public.teams(id) on delete cascade,
  fixtures_played int not null default 0,
  won int not null default 0,
  drawn int not null default 0,
  lost int not null default 0,
  goals_for int not null default 0,
  goals_against int not null default 0,
  goals_difference int not null default 0,
  points int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (competition_id, season_id, "group", team_id)
);

create index if not exists idx_matches_competition_fixture
  on public.matches (competition_id, fixture);

create index if not exists idx_matches_competition_stage
  on public.matches (competition_id, stage);

create index if not exists idx_matches_competition_stage_group
  on public.matches (competition_id, stage, "group");

create index if not exists idx_predictions_league_member_match
  on public.predictions (league_member_id, match_id);

create index if not exists idx_competition_group_standings_lookup
  on public.competition_group_standings (competition_id, season_id, "group", position);

create unique index if not exists uniq_competition_group_standings_team
  on public.competition_group_standings (competition_id, coalesce(season_id, -1), "group", team_id);

alter table public.competition_group_standings enable row level security;

drop policy if exists "Admin: Full access to competition group standings"
  on public.competition_group_standings;

create policy "Admin: Full access to competition group standings"
  on public.competition_group_standings for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Users: Read competition group standings"
  on public.competition_group_standings;

create policy "Users: Read competition group standings"
  on public.competition_group_standings for select
  to authenticated
  using (true);
