/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        primaryForeground: 'var(--color-primary-foreground)',
        primarySoft: 'var(--color-primary-soft)',
        background: 'var(--color-background)',
        backgroundSecondary: 'var(--color-background-secondary)',
        surface: 'var(--color-surface)',
        surfaceSoft: 'var(--color-surface-soft)',
        surfaceElevated: 'var(--color-surface-elevated)',
        surfaceSecondary: 'var(--color-surface-soft)',
        border: 'var(--color-border)',
        borderStrong: 'var(--color-border-strong)',
        text: 'var(--color-text)',
        textSecondary: 'var(--color-text-secondary)',
        muted: 'var(--color-muted)',
        mutedForeground: 'var(--color-muted-foreground)',
        error: 'var(--color-error)',
        errorSoft: 'var(--color-error-soft)',
        success: 'var(--color-success)',
        successSoft: 'var(--color-success-soft)',
        warning: 'var(--color-warning)',
        warningSoft: 'var(--color-warning-soft)',
        info: 'var(--color-info)',
        infoSoft: 'var(--color-info-soft)',
        secondary: 'var(--color-secondary)',
        overlay: 'var(--color-overlay)',
        soft: 'var(--color-background-secondary)',
      },
      fontFamily: {
        teko: ['Teko_400Regular'],
        'teko-bold': ['Teko_700Bold'],
      },

      maxWidth: {
        sm: '400px',
        md: '680px',
        lg: '900px',
        xl: '1280px',
      },
    },
  },
  plugins: [],
};
