// Get Teams All List by League ID
export const response = {
  status: 'success',
  response: {
    list: [
      {
        name: 'Bayern München',
        shortName: 'Bayern München',
        id: 9823,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 26,
        draws: 5,
        losses: 1,
        scoresStr: '116-35',
        goalConDiff: 81,
        pts: 83,
        idx: 1,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9823_large.png',
      },
      {
        name: 'Borussia Dortmund',
        shortName: 'Dortmund',
        id: 9789,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 20,
        draws: 7,
        losses: 5,
        scoresStr: '65-32',
        goalConDiff: 33,
        pts: 67,
        idx: 2,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9789_large.png',
      },
      {
        name: 'RB Leipzig',
        shortName: 'RB Leipzig',
        id: 178475,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 19,
        draws: 5,
        losses: 8,
        scoresStr: '63-42',
        goalConDiff: 21,
        pts: 62,
        idx: 3,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/178475_large.png',
      },
      {
        name: 'Bayer Leverkusen',
        shortName: 'Leverkusen',
        id: 8178,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 17,
        draws: 7,
        losses: 8,
        scoresStr: '66-43',
        goalConDiff: 23,
        pts: 58,
        idx: 4,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8178_large.png',
      },
      {
        name: 'VfB Stuttgart',
        shortName: 'VfB Stuttgart',
        id: 10269,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 17,
        draws: 7,
        losses: 8,
        scoresStr: '66-46',
        goalConDiff: 20,
        pts: 58,
        idx: 5,
        qualColor: '#0046A7',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/10269_large.png',
      },
      {
        name: 'Hoffenheim',
        shortName: 'Hoffenheim',
        id: 8226,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 17,
        draws: 7,
        losses: 8,
        scoresStr: '64-48',
        goalConDiff: 16,
        pts: 58,
        idx: 6,
        qualColor: '#0046A7',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8226_large.png',
      },
      {
        name: 'Freiburg',
        shortName: 'Freiburg',
        id: 8358,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 12,
        draws: 8,
        losses: 12,
        scoresStr: '45-53',
        goalConDiff: -8,
        pts: 44,
        idx: 7,
        qualColor: '#02CCF0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8358_large.png',
      },
      {
        name: 'Eintracht Frankfurt',
        shortName: 'Frankfurt',
        id: 9810,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 11,
        draws: 10,
        losses: 11,
        scoresStr: '57-60',
        goalConDiff: -3,
        pts: 43,
        idx: 8,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9810_large.png',
      },
      {
        name: 'Augsburg',
        shortName: 'Augsburg',
        id: 8406,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 11,
        draws: 7,
        losses: 14,
        scoresStr: '42-56',
        goalConDiff: -14,
        pts: 40,
        idx: 9,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8406_large.png',
      },
      {
        name: 'Mainz 05',
        shortName: 'Mainz',
        id: 9905,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 9,
        draws: 10,
        losses: 13,
        scoresStr: '41-50',
        goalConDiff: -9,
        pts: 37,
        idx: 10,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9905_large.png',
      },
      {
        name: 'Borussia Mönchengladbach',
        shortName: "M'gladbach",
        id: 9788,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 8,
        draws: 11,
        losses: 13,
        scoresStr: '37-50',
        goalConDiff: -13,
        pts: 35,
        idx: 11,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9788_large.png',
      },
      {
        name: 'Hamburger SV',
        shortName: 'Hamburger SV',
        id: 9790,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 8,
        draws: 10,
        losses: 14,
        scoresStr: '36-51',
        goalConDiff: -15,
        pts: 34,
        idx: 12,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9790_large.png',
      },
      {
        name: 'Union Berlin',
        shortName: 'Union Berlin',
        id: 8149,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 8,
        draws: 9,
        losses: 15,
        scoresStr: '37-57',
        goalConDiff: -20,
        pts: 33,
        idx: 13,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8149_large.png',
      },
      {
        name: '1. FC Köln',
        shortName: 'Köln',
        id: 8722,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 7,
        draws: 11,
        losses: 14,
        scoresStr: '47-55',
        goalConDiff: -8,
        pts: 32,
        idx: 14,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8722_large.png',
      },
      {
        name: 'Werder Bremen',
        shortName: 'Werder Bremen',
        id: 8697,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 8,
        draws: 8,
        losses: 16,
        scoresStr: '37-57',
        goalConDiff: -20,
        pts: 32,
        idx: 15,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8697_large.png',
      },
      {
        name: 'Wolfsburg',
        shortName: 'Wolfsburg',
        id: 8721,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 6,
        draws: 8,
        losses: 18,
        scoresStr: '42-67',
        goalConDiff: -25,
        pts: 26,
        idx: 16,
        qualColor: '#FFA72F',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8721_large.png',
      },
      {
        name: 'St. Pauli',
        shortName: 'St. Pauli',
        id: 8152,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 6,
        draws: 8,
        losses: 18,
        scoresStr: '27-55',
        goalConDiff: -28,
        pts: 26,
        idx: 17,
        qualColor: '#FF4646',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8152_large.png',
      },
      {
        name: 'FC Heidenheim',
        shortName: 'FC Heidenheim',
        id: 94937,
        deduction: null,
        ongoing: null,
        played: 32,
        wins: 5,
        draws: 8,
        losses: 19,
        scoresStr: '38-69',
        goalConDiff: -31,
        pts: 23,
        idx: 18,
        qualColor: '#FF4646',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/94937_large.png',
      },
    ],
  },
};
