// Get Teams by League ID
export const response = {
  status: 'success',
  response: {
    list: [
      {
        name: 'Bayern München',
        shortName: 'Bayern München',
        id: 9823,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 4,
        draws: 0,
        losses: 0,
        scoresStr: '12-2',
        goalConDiff: 10,
        goalsScored: 12,
        pts: 12,
        idx: 1,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9823_large.png',
      },
      {
        name: 'Tottenham Hotspur',
        shortName: 'Tottenham',
        id: 8586,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 4,
        draws: 0,
        losses: 0,
        scoresStr: '10-0',
        goalConDiff: 10,
        goalsScored: 10,
        pts: 12,
        idx: 2,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8586_large.png',
      },
      {
        name: 'Arsenal',
        shortName: 'Arsenal',
        id: 9825,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 4,
        draws: 0,
        losses: 0,
        scoresStr: '12-3',
        goalConDiff: 9,
        goalsScored: 12,
        pts: 12,
        idx: 3,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9825_large.png',
      },
      {
        name: 'Chelsea',
        shortName: 'Chelsea',
        id: 8455,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 4,
        draws: 0,
        losses: 0,
        scoresStr: '10-1',
        goalConDiff: 9,
        goalsScored: 10,
        pts: 12,
        idx: 4,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8455_large.png',
      },
      {
        name: 'Sporting CP',
        shortName: 'Sporting CP',
        id: 9768,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 4,
        draws: 0,
        losses: 0,
        scoresStr: '11-3',
        goalConDiff: 8,
        goalsScored: 11,
        pts: 12,
        idx: 5,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9768_large.png',
      },
      {
        name: 'Barcelona',
        shortName: 'Barcelona',
        id: 8634,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 3,
        draws: 0,
        losses: 1,
        scoresStr: '13-5',
        goalConDiff: 8,
        goalsScored: 13,
        pts: 9,
        idx: 6,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8634_large.png',
      },
      {
        name: 'Newcastle United',
        shortName: 'Newcastle',
        id: 10261,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 3,
        draws: 0,
        losses: 1,
        scoresStr: '9-2',
        goalConDiff: 7,
        goalsScored: 9,
        pts: 9,
        idx: 7,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/10261_large.png',
      },
      {
        name: 'Atletico Madrid',
        shortName: 'Atletico Madrid',
        id: 9906,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 3,
        draws: 0,
        losses: 1,
        scoresStr: '11-5',
        goalConDiff: 6,
        goalsScored: 11,
        pts: 9,
        idx: 8,
        qualColor: '#2AD572',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9906_large.png',
      },
      {
        name: 'Real Madrid',
        shortName: 'Real Madrid',
        id: 8633,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 3,
        draws: 0,
        losses: 1,
        scoresStr: '10-4',
        goalConDiff: 6,
        goalsScored: 10,
        pts: 9,
        idx: 9,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8633_large.png',
      },
      {
        name: 'Liverpool',
        shortName: 'Liverpool',
        id: 8650,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 3,
        draws: 0,
        losses: 1,
        scoresStr: '11-6',
        goalConDiff: 5,
        goalsScored: 11,
        pts: 9,
        idx: 10,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8650_large.png',
      },
      {
        name: 'Manchester City',
        shortName: 'Man City',
        id: 8456,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 3,
        draws: 0,
        losses: 1,
        scoresStr: '8-3',
        goalConDiff: 5,
        goalsScored: 8,
        pts: 9,
        idx: 11,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8456_large.png',
      },
      {
        name: 'Juventus',
        shortName: 'Juventus',
        id: 9885,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 2,
        losses: 0,
        scoresStr: '9-5',
        goalConDiff: 4,
        goalsScored: 9,
        pts: 8,
        idx: 12,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9885_large.png',
      },
      {
        name: 'Paris Saint-Germain',
        shortName: 'PSG',
        id: 9847,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '11-6',
        goalConDiff: 5,
        goalsScored: 11,
        pts: 7,
        idx: 13,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9847_large.png',
      },
      {
        name: 'Borussia Dortmund',
        shortName: 'Dortmund',
        id: 9789,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '10-5',
        goalConDiff: 5,
        goalsScored: 10,
        pts: 7,
        idx: 14,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9789_large.png',
      },
      {
        name: 'Club Brugge',
        shortName: 'Club Brugge',
        id: 8342,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '10-7',
        goalConDiff: 3,
        goalsScored: 10,
        pts: 7,
        idx: 15,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8342_large.png',
      },
      {
        name: 'Napoli',
        shortName: 'Napoli',
        id: 9875,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '6-4',
        goalConDiff: 2,
        goalsScored: 6,
        pts: 7,
        idx: 16,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9875_large.png',
      },
      {
        name: 'Galatasaray',
        shortName: 'Galatasaray',
        id: 8637,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '5-3',
        goalConDiff: 2,
        goalsScored: 5,
        pts: 7,
        idx: 17,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8637_large.png',
      },
      {
        name: 'Qarabag FK',
        shortName: 'Qarabag FK',
        id: 7981,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '9-8',
        goalConDiff: 1,
        goalsScored: 9,
        pts: 7,
        idx: 18,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/7981_large.png',
      },
      {
        name: 'Atalanta',
        shortName: 'Atalanta',
        id: 8524,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '6-5',
        goalConDiff: 1,
        goalsScored: 6,
        pts: 7,
        idx: 19,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8524_large.png',
      },
      {
        name: 'Pafos FC',
        shortName: 'Pafos FC',
        id: 2137,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 1,
        losses: 1,
        scoresStr: '8-8',
        goalConDiff: 0,
        goalsScored: 8,
        pts: 7,
        idx: 20,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/2137_large.png',
      },
      {
        name: 'Benfica',
        shortName: 'Benfica',
        id: 9772,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 0,
        losses: 2,
        scoresStr: '8-6',
        goalConDiff: 2,
        goalsScored: 8,
        pts: 6,
        idx: 21,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9772_large.png',
      },
      {
        name: 'Inter',
        shortName: 'Inter',
        id: 8636,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 0,
        losses: 2,
        scoresStr: '6-5',
        goalConDiff: 1,
        goalsScored: 6,
        pts: 6,
        idx: 22,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8636_large.png',
      },
      {
        name: 'Marseille',
        shortName: 'Marseille',
        id: 8592,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 2,
        draws: 0,
        losses: 2,
        scoresStr: '6-5',
        goalConDiff: 1,
        goalsScored: 6,
        pts: 6,
        idx: 23,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8592_large.png',
      },
      {
        name: 'Monaco',
        shortName: 'Monaco',
        id: 9829,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 3,
        losses: 0,
        scoresStr: '3-2',
        goalConDiff: 1,
        goalsScored: 3,
        pts: 6,
        idx: 24,
        qualColor: '#0294F0',
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9829_large.png',
      },
      {
        name: 'Olympiacos',
        shortName: 'Olympiacos',
        id: 8638,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 2,
        losses: 1,
        scoresStr: '6-5',
        goalConDiff: 1,
        goalsScored: 6,
        pts: 5,
        idx: 25,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8638_large.png',
      },
      {
        name: 'FC København',
        shortName: 'FC København',
        id: 8391,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 2,
        losses: 1,
        scoresStr: '8-9',
        goalConDiff: -1,
        goalsScored: 8,
        pts: 5,
        idx: 26,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8391_large.png',
      },
      {
        name: 'Bayer Leverkusen',
        shortName: 'Leverkusen',
        id: 8178,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 2,
        losses: 1,
        scoresStr: '8-10',
        goalConDiff: -2,
        goalsScored: 8,
        pts: 5,
        idx: 27,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8178_large.png',
      },
      {
        name: 'Bodø/Glimt',
        shortName: 'Bodø/Glimt',
        id: 8402,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 1,
        losses: 2,
        scoresStr: '7-7',
        goalConDiff: 0,
        goalsScored: 7,
        pts: 4,
        idx: 28,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8402_large.png',
      },
      {
        name: 'Athletic Club',
        shortName: 'Athletic Club',
        id: 8315,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 1,
        losses: 2,
        scoresStr: '5-6',
        goalConDiff: -1,
        goalsScored: 5,
        pts: 4,
        idx: 29,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8315_large.png',
      },
      {
        name: 'PSV Eindhoven',
        shortName: 'PSV Eindhoven',
        id: 8640,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 0,
        losses: 3,
        scoresStr: '10-10',
        goalConDiff: 0,
        goalsScored: 10,
        pts: 3,
        idx: 30,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8640_large.png',
      },
      {
        name: 'Eintracht Frankfurt',
        shortName: 'Frankfurt',
        id: 9810,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 0,
        losses: 3,
        scoresStr: '6-11',
        goalConDiff: -5,
        goalsScored: 6,
        pts: 3,
        idx: 31,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/9810_large.png',
      },
      {
        name: 'Union St.Gilloise',
        shortName: 'Union St.Gilloise',
        id: 7978,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 1,
        draws: 0,
        losses: 3,
        scoresStr: '3-11',
        goalConDiff: -8,
        goalsScored: 3,
        pts: 3,
        idx: 32,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/7978_large.png',
      },
      {
        name: 'Slavia Prague',
        shortName: 'Slavia Prague',
        id: 7787,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 0,
        draws: 2,
        losses: 2,
        scoresStr: '4-9',
        goalConDiff: -5,
        goalsScored: 4,
        pts: 2,
        idx: 33,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/7787_large.png',
      },
      {
        name: 'Villarreal',
        shortName: 'Villarreal',
        id: 10205,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 0,
        draws: 1,
        losses: 3,
        scoresStr: '5-9',
        goalConDiff: -4,
        goalsScored: 5,
        pts: 1,
        idx: 34,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/10205_large.png',
      },
      {
        name: 'Kairat Almaty',
        shortName: 'Kairat Almaty',
        id: 8037,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 0,
        draws: 1,
        losses: 3,
        scoresStr: '1-10',
        goalConDiff: -9,
        goalsScored: 1,
        pts: 1,
        idx: 35,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8037_large.png',
      },
      {
        name: 'Ajax',
        shortName: 'Ajax',
        id: 8593,
        deduction: null,
        ongoing: null,
        played: 4,
        wins: 0,
        draws: 0,
        losses: 4,
        scoresStr: '1-9',
        goalConDiff: -8,
        goalsScored: 1,
        pts: 0,
        idx: 36,
        qualColor: null,
        logo: 'https://images.fotmob.com/image_resources/logo/teamlogo/8593_large.png',
      },
    ],
  },
};
