// Official logo-only button artwork generated by Apple's Sign in with Apple endpoint
// at 52pt, white, 14pt corner radius and 3x scale. Keep its built-in padding intact.
import { images } from '@/assets/images';
import { createLegalAcceptanceContext, recordSocialLegalAcceptance } from '@/features/auth/legalAcceptance';
import { useTranslation } from '@/hooks/useTranslation';
import { supabase } from '@/lib/supabase';
import { formatErrorForUser } from '@/utils/errorFormats';
import * as AppleAuthentication from 'expo-apple-authentication';
import { useCallback, useEffect, useState } from 'react';
import { Image } from 'expo-image';
import { Alert, Platform, Pressable, StyleSheet } from 'react-native';

const AppleAuth = ({
  setIsLoading,
  isLoading,
  mode = 'signIn',
  legalAccepted,
}: {
  setIsLoading: (isLoading: boolean) => void;
  isLoading: boolean;
  mode?: 'signIn' | 'signUp';
  legalAccepted: boolean;
}) => {
  const { t } = useTranslation();
  const [available, setAvailable] = useState(false);

  useEffect(() => {
    if (Platform.OS !== 'ios') return;
    let cancelled = false;
    AppleAuthentication.isAvailableAsync()
      .then((ok) => {
        if (!cancelled) setAvailable(ok);
      })
      .catch(() => {
        if (!cancelled) setAvailable(false);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const handleAppleSignIn = useCallback(async () => {
    if (isLoading || !legalAccepted) return;

    try {
      setIsLoading(true);

      const credential = await AppleAuthentication.signInAsync({
        requestedScopes: [
          AppleAuthentication.AppleAuthenticationScope.FULL_NAME,
          AppleAuthentication.AppleAuthenticationScope.EMAIL,
        ],
      });

      if (!credential.identityToken) {
        throw new Error('Apple did not return identityToken');
      }

      const { data, error } = await supabase.auth.signInWithIdToken({
        provider: 'apple',
        token: credential.identityToken,
      });

      if (error) throw error;

      if (!data?.session?.user?.id) {
        throw new Error('Failed to create session after Apple sign in');
      }

      try {
        await recordSocialLegalAcceptance(
          createLegalAcceptanceContext(
            'apple',
            mode === 'signUp' ? 'sign_up' : 'social_continue',
          ),
        );
      } catch (acceptanceError) {
        await supabase.auth.signOut();
        throw acceptanceError;
      }

      const fullName = [credential.fullName?.givenName, credential.fullName?.familyName].filter(Boolean).join(' ');

      if (fullName) {
        const { error: updateAuthError } = await supabase.auth.updateUser({
          data: { full_name: fullName },
        });
        if (updateAuthError) throw updateAuthError;
      }
    } catch (error: unknown) {
      if (
        typeof error === 'object' &&
        error !== null &&
        'code' in error &&
        (error as { code: string }).code === 'ERR_REQUEST_CANCELED'
      ) {
        return;
      }

      const userMessage = formatErrorForUser(error) || 'Apple sign in failed. Please try again.';
      Alert.alert(t('Sign In Error'), t(userMessage));
    } finally {
      setIsLoading(false);
    }
  }, [isLoading, legalAccepted, mode, setIsLoading, t]);

  if (Platform.OS !== 'ios' || !available) {
    return null;
  }

  const label = t(mode === 'signUp' ? 'Sign up with Apple' : 'Sign in with Apple');

  return (
    <Pressable
      testID="apple-sign-in-button"
      disabled={isLoading || !legalAccepted}
      accessibilityLabel={label}
      accessibilityRole="button"
      accessibilityHint={label}
      accessibilityState={{ disabled: isLoading || !legalAccepted, busy: isLoading }}
      onPress={handleAppleSignIn}
      style={({ pressed }) => [
        styles.button,
        (isLoading || !legalAccepted) && styles.disabled,
        pressed && styles.pressed,
      ]}
    >
      <Image
        testID="apple-sign-in-logo"
        accessible={false}
        source={images.appleWhiteLogo}
        contentFit="contain"
        style={styles.logo}
      />
    </Pressable>
  );
};

const styles = StyleSheet.create({
  button: {
    width: 52,
    height: 52,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'black',
    overflow: 'hidden',
  },
  logo: {
    width: 52,
    height: 52,
  },
  disabled: {
    opacity: 0.5,
  },
  pressed: {
    opacity: 0.85,
    transform: [{ scale: 0.985 }],
  },
});

export default AppleAuth;
