-- Create competitions table
CREATE TABLE IF NOT EXISTS public.competitions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  api_id TEXT NOT NULL,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  type TEXT,
  logo TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMP NOT NULL DEFAULT now(),
  area TEXT,
  flag TEXT,
  competition_start_date TEXT NOT NULL,
  competition_end_date TEXT NOT NULL,
  current_matchday SMALLINT
);

-- Enable Row Level Security
ALTER TABLE public.competitions ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Competitions are viewable by everyone."
  ON public.competitions
  FOR SELECT
  USING (true); 